# Generated by Django 2.0.7 on 2018-07-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtree',
            name='parent',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
