# Generated by Django 2.0.7 on 2018-07-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_playtree_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtree',
            name='parent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
