# Generated by Django 2.0.7 on 2018-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180720_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtree',
            name='parent',
            field=models.SmallIntegerField(null=True),
        ),
    ]
