# Generated by Django 2.0.7 on 2018-07-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180720_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playtree',
            name='parent',
        ),
    ]
