# Generated by Django 2.0.7 on 2018-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_playtree_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtree',
            name='parent',
            field=models.SmallIntegerField(default=0),
        ),
    ]
