# Generated by Django 2.0.7 on 2018-07-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_playtree_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='playbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('projectid', models.IntegerField()),
                ('ischild', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('childid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PlayTree',
        ),
    ]
