# Generated by Django 2.0.7 on 2018-07-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='projectid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
