# Generated by Django 2.0.7 on 2018-07-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_relations_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('projectid', models.IntegerField()),
            ],
        ),
    ]
