# Generated by Django 2.0.7 on 2018-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180726_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ident', models.IntegerField()),
            ],
        ),
    ]
