# Generated by Django 2.0.7 on 2018-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='currentplay',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
