# Generated by Django 2.0.7 on 2018-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20180806_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
