# Generated by Django 2.0.7 on 2018-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20180806_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='projectid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
