# Generated by Django 2.0.7 on 2018-08-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_build_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='filename',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
