# Generated by Django 2.0.7 on 2018-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_inventories_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildstep',
            name='bsiid',
        ),
        migrations.AddField(
            model_name='buildstep',
            name='path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
