# Generated by Django 2.0.7 on 2018-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20180809_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='procname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
